# test using secrets for project properties
name: Test Project Properties from a GH Actions Secret

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.4
    - name: Build with Gradle
      env:
          PROJ_PROP_1: ${{secrets.PP1}}
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          proj_prop
          -Ppprop1="${{env.PROJ_PROP_1}}"
